/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriggerRouteImport } from './routes/trigger'
import { Route as TestShortcutRouteImport } from './routes/test-shortcut'
import { Route as TestNewShortcutRouteImport } from './routes/test-new-shortcut'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShortcutSetupRouteImport } from './routes/shortcut-setup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NewShortcutTokenRouteImport } from './routes/new-shortcut-token'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AddFirstContactRouteImport } from './routes/add-first-contact'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TestTrackingAlertIdRouteImport } from './routes/testTracking.$alertId'
import { Route as TestGpsAlertIdRouteImport } from './routes/testGps.$alertId'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ContactsAddRouteImport } from './routes/contacts_.add'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'
import { Route as AdminUserManagementRouteImport } from './routes/admin.userManagement'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLiveMonitoringRouteImport } from './routes/admin.liveMonitoring'
import { Route as AdminEmergencyLogsRouteImport } from './routes/admin.emergencyLogs'
import { Route as TrackAlertIdTrackingTokenRouteImport } from './routes/track.$alertId.$trackingToken'
import { Route as ContactsEditContactIdRouteImport } from './routes/contacts_.edit.$contactId'
import { Route as AdminLiveMonitoringAlertIdRouteImport } from './routes/admin.liveMonitoring_.$alertId'
import { Route as AdminEmergencyLogsAlertIdRouteImport } from './routes/admin.emergencyLogs_.$alertId'
import { Route as AdminUserManagementUserIdViewRouteImport } from './routes/admin.userManagement_.$userId.view'
import { Route as AdminUserManagementUserIdEditRouteImport } from './routes/admin.userManagement_.$userId.edit'

const TriggerRoute = TriggerRouteImport.update({
  id: '/trigger',
  path: '/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const TestShortcutRoute = TestShortcutRouteImport.update({
  id: '/test-shortcut',
  path: '/test-shortcut',
  getParentRoute: () => rootRouteImport,
} as any)
const TestNewShortcutRoute = TestNewShortcutRouteImport.update({
  id: '/test-new-shortcut',
  path: '/test-new-shortcut',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortcutSetupRoute = ShortcutSetupRouteImport.update({
  id: '/shortcut-setup',
  path: '/shortcut-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NewShortcutTokenRoute = NewShortcutTokenRouteImport.update({
  id: '/new-shortcut-token',
  path: '/new-shortcut-token',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AddFirstContactRoute = AddFirstContactRouteImport.update({
  id: '/add-first-contact',
  path: '/add-first-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TestTrackingAlertIdRoute = TestTrackingAlertIdRouteImport.update({
  id: '/testTracking/$alertId',
  path: '/testTracking/$alertId',
  getParentRoute: () => rootRouteImport,
} as any)
const TestGpsAlertIdRoute = TestGpsAlertIdRouteImport.update({
  id: '/testGps/$alertId',
  path: '/testGps/$alertId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsAddRoute = ContactsAddRouteImport.update({
  id: '/contacts_/add',
  path: '/contacts/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserManagementRoute = AdminUserManagementRouteImport.update({
  id: '/userManagement',
  path: '/userManagement',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveMonitoringRoute = AdminLiveMonitoringRouteImport.update({
  id: '/liveMonitoring',
  path: '/liveMonitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmergencyLogsRoute = AdminEmergencyLogsRouteImport.update({
  id: '/emergencyLogs',
  path: '/emergencyLogs',
  getParentRoute: () => AdminRoute,
} as any)
const TrackAlertIdTrackingTokenRoute =
  TrackAlertIdTrackingTokenRouteImport.update({
    id: '/track/$alertId/$trackingToken',
    path: '/track/$alertId/$trackingToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContactsEditContactIdRoute = ContactsEditContactIdRouteImport.update({
  id: '/contacts_/edit/$contactId',
  path: '/contacts/edit/$contactId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLiveMonitoringAlertIdRoute =
  AdminLiveMonitoringAlertIdRouteImport.update({
    id: '/liveMonitoring_/$alertId',
    path: '/liveMonitoring/$alertId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminEmergencyLogsAlertIdRoute =
  AdminEmergencyLogsAlertIdRouteImport.update({
    id: '/emergencyLogs_/$alertId',
    path: '/emergencyLogs/$alertId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminUserManagementUserIdViewRoute =
  AdminUserManagementUserIdViewRouteImport.update({
    id: '/userManagement_/$userId/view',
    path: '/userManagement/$userId/view',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminUserManagementUserIdEditRoute =
  AdminUserManagementUserIdEditRouteImport.update({
    id: '/userManagement_/$userId/edit',
    path: '/userManagement/$userId/edit',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-first-contact': typeof AddFirstContactRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/new-shortcut-token': typeof NewShortcutTokenRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shortcut-setup': typeof ShortcutSetupRoute
  '/signup': typeof SignupRoute
  '/test-new-shortcut': typeof TestNewShortcutRoute
  '/test-shortcut': typeof TestShortcutRoute
  '/trigger': typeof TriggerRoute
  '/admin/emergencyLogs': typeof AdminEmergencyLogsRoute
  '/admin/liveMonitoring': typeof AdminLiveMonitoringRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/userManagement': typeof AdminUserManagementRoute
  '/admin/login': typeof AdminLoginRoute
  '/contacts/add': typeof ContactsAddRoute
  '/profile/edit': typeof ProfileEditRoute
  '/testGps/$alertId': typeof TestGpsAlertIdRoute
  '/testTracking/$alertId': typeof TestTrackingAlertIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/emergencyLogs/$alertId': typeof AdminEmergencyLogsAlertIdRoute
  '/admin/liveMonitoring/$alertId': typeof AdminLiveMonitoringAlertIdRoute
  '/contacts/edit/$contactId': typeof ContactsEditContactIdRoute
  '/track/$alertId/$trackingToken': typeof TrackAlertIdTrackingTokenRoute
  '/admin/userManagement/$userId/edit': typeof AdminUserManagementUserIdEditRoute
  '/admin/userManagement/$userId/view': typeof AdminUserManagementUserIdViewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-first-contact': typeof AddFirstContactRoute
  '/contacts': typeof ContactsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/new-shortcut-token': typeof NewShortcutTokenRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shortcut-setup': typeof ShortcutSetupRoute
  '/signup': typeof SignupRoute
  '/test-new-shortcut': typeof TestNewShortcutRoute
  '/test-shortcut': typeof TestShortcutRoute
  '/trigger': typeof TriggerRoute
  '/admin/emergencyLogs': typeof AdminEmergencyLogsRoute
  '/admin/liveMonitoring': typeof AdminLiveMonitoringRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/userManagement': typeof AdminUserManagementRoute
  '/admin/login': typeof AdminLoginRoute
  '/contacts/add': typeof ContactsAddRoute
  '/profile/edit': typeof ProfileEditRoute
  '/testGps/$alertId': typeof TestGpsAlertIdRoute
  '/testTracking/$alertId': typeof TestTrackingAlertIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/emergencyLogs/$alertId': typeof AdminEmergencyLogsAlertIdRoute
  '/admin/liveMonitoring/$alertId': typeof AdminLiveMonitoringAlertIdRoute
  '/contacts/edit/$contactId': typeof ContactsEditContactIdRoute
  '/track/$alertId/$trackingToken': typeof TrackAlertIdTrackingTokenRoute
  '/admin/userManagement/$userId/edit': typeof AdminUserManagementUserIdEditRoute
  '/admin/userManagement/$userId/view': typeof AdminUserManagementUserIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-first-contact': typeof AddFirstContactRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/new-shortcut-token': typeof NewShortcutTokenRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shortcut-setup': typeof ShortcutSetupRoute
  '/signup': typeof SignupRoute
  '/test-new-shortcut': typeof TestNewShortcutRoute
  '/test-shortcut': typeof TestShortcutRoute
  '/trigger': typeof TriggerRoute
  '/admin/emergencyLogs': typeof AdminEmergencyLogsRoute
  '/admin/liveMonitoring': typeof AdminLiveMonitoringRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/userManagement': typeof AdminUserManagementRoute
  '/admin_/login': typeof AdminLoginRoute
  '/contacts_/add': typeof ContactsAddRoute
  '/profile/edit': typeof ProfileEditRoute
  '/testGps/$alertId': typeof TestGpsAlertIdRoute
  '/testTracking/$alertId': typeof TestTrackingAlertIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/emergencyLogs_/$alertId': typeof AdminEmergencyLogsAlertIdRoute
  '/admin/liveMonitoring_/$alertId': typeof AdminLiveMonitoringAlertIdRoute
  '/contacts_/edit/$contactId': typeof ContactsEditContactIdRoute
  '/track/$alertId/$trackingToken': typeof TrackAlertIdTrackingTokenRoute
  '/admin/userManagement_/$userId/edit': typeof AdminUserManagementUserIdEditRoute
  '/admin/userManagement_/$userId/view': typeof AdminUserManagementUserIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-first-contact'
    | '/admin'
    | '/contacts'
    | '/forgot-password'
    | '/help'
    | '/history'
    | '/home'
    | '/how-it-works'
    | '/login'
    | '/new-shortcut-token'
    | '/notifications'
    | '/privacy'
    | '/settings'
    | '/setup'
    | '/shortcut-setup'
    | '/signup'
    | '/test-new-shortcut'
    | '/test-shortcut'
    | '/trigger'
    | '/admin/emergencyLogs'
    | '/admin/liveMonitoring'
    | '/admin/settings'
    | '/admin/userManagement'
    | '/admin/login'
    | '/contacts/add'
    | '/profile/edit'
    | '/testGps/$alertId'
    | '/testTracking/$alertId'
    | '/admin/'
    | '/admin/emergencyLogs/$alertId'
    | '/admin/liveMonitoring/$alertId'
    | '/contacts/edit/$contactId'
    | '/track/$alertId/$trackingToken'
    | '/admin/userManagement/$userId/edit'
    | '/admin/userManagement/$userId/view'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-first-contact'
    | '/contacts'
    | '/forgot-password'
    | '/help'
    | '/history'
    | '/home'
    | '/how-it-works'
    | '/login'
    | '/new-shortcut-token'
    | '/notifications'
    | '/privacy'
    | '/settings'
    | '/setup'
    | '/shortcut-setup'
    | '/signup'
    | '/test-new-shortcut'
    | '/test-shortcut'
    | '/trigger'
    | '/admin/emergencyLogs'
    | '/admin/liveMonitoring'
    | '/admin/settings'
    | '/admin/userManagement'
    | '/admin/login'
    | '/contacts/add'
    | '/profile/edit'
    | '/testGps/$alertId'
    | '/testTracking/$alertId'
    | '/admin'
    | '/admin/emergencyLogs/$alertId'
    | '/admin/liveMonitoring/$alertId'
    | '/contacts/edit/$contactId'
    | '/track/$alertId/$trackingToken'
    | '/admin/userManagement/$userId/edit'
    | '/admin/userManagement/$userId/view'
  id:
    | '__root__'
    | '/'
    | '/add-first-contact'
    | '/admin'
    | '/contacts'
    | '/forgot-password'
    | '/help'
    | '/history'
    | '/home'
    | '/how-it-works'
    | '/login'
    | '/new-shortcut-token'
    | '/notifications'
    | '/privacy'
    | '/settings'
    | '/setup'
    | '/shortcut-setup'
    | '/signup'
    | '/test-new-shortcut'
    | '/test-shortcut'
    | '/trigger'
    | '/admin/emergencyLogs'
    | '/admin/liveMonitoring'
    | '/admin/settings'
    | '/admin/userManagement'
    | '/admin_/login'
    | '/contacts_/add'
    | '/profile/edit'
    | '/testGps/$alertId'
    | '/testTracking/$alertId'
    | '/admin/'
    | '/admin/emergencyLogs_/$alertId'
    | '/admin/liveMonitoring_/$alertId'
    | '/contacts_/edit/$contactId'
    | '/track/$alertId/$trackingToken'
    | '/admin/userManagement_/$userId/edit'
    | '/admin/userManagement_/$userId/view'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddFirstContactRoute: typeof AddFirstContactRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  NewShortcutTokenRoute: typeof NewShortcutTokenRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ShortcutSetupRoute: typeof ShortcutSetupRoute
  SignupRoute: typeof SignupRoute
  TestNewShortcutRoute: typeof TestNewShortcutRoute
  TestShortcutRoute: typeof TestShortcutRoute
  TriggerRoute: typeof TriggerRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ContactsAddRoute: typeof ContactsAddRoute
  ProfileEditRoute: typeof ProfileEditRoute
  TestGpsAlertIdRoute: typeof TestGpsAlertIdRoute
  TestTrackingAlertIdRoute: typeof TestTrackingAlertIdRoute
  ContactsEditContactIdRoute: typeof ContactsEditContactIdRoute
  TrackAlertIdTrackingTokenRoute: typeof TrackAlertIdTrackingTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trigger': {
      id: '/trigger'
      path: '/trigger'
      fullPath: '/trigger'
      preLoaderRoute: typeof TriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-shortcut': {
      id: '/test-shortcut'
      path: '/test-shortcut'
      fullPath: '/test-shortcut'
      preLoaderRoute: typeof TestShortcutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-new-shortcut': {
      id: '/test-new-shortcut'
      path: '/test-new-shortcut'
      fullPath: '/test-new-shortcut'
      preLoaderRoute: typeof TestNewShortcutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortcut-setup': {
      id: '/shortcut-setup'
      path: '/shortcut-setup'
      fullPath: '/shortcut-setup'
      preLoaderRoute: typeof ShortcutSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new-shortcut-token': {
      id: '/new-shortcut-token'
      path: '/new-shortcut-token'
      fullPath: '/new-shortcut-token'
      preLoaderRoute: typeof NewShortcutTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-first-contact': {
      id: '/add-first-contact'
      path: '/add-first-contact'
      fullPath: '/add-first-contact'
      preLoaderRoute: typeof AddFirstContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/testTracking/$alertId': {
      id: '/testTracking/$alertId'
      path: '/testTracking/$alertId'
      fullPath: '/testTracking/$alertId'
      preLoaderRoute: typeof TestTrackingAlertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testGps/$alertId': {
      id: '/testGps/$alertId'
      path: '/testGps/$alertId'
      fullPath: '/testGps/$alertId'
      preLoaderRoute: typeof TestGpsAlertIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts_/add': {
      id: '/contacts_/add'
      path: '/contacts/add'
      fullPath: '/contacts/add'
      preLoaderRoute: typeof ContactsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/userManagement': {
      id: '/admin/userManagement'
      path: '/userManagement'
      fullPath: '/admin/userManagement'
      preLoaderRoute: typeof AdminUserManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/liveMonitoring': {
      id: '/admin/liveMonitoring'
      path: '/liveMonitoring'
      fullPath: '/admin/liveMonitoring'
      preLoaderRoute: typeof AdminLiveMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emergencyLogs': {
      id: '/admin/emergencyLogs'
      path: '/emergencyLogs'
      fullPath: '/admin/emergencyLogs'
      preLoaderRoute: typeof AdminEmergencyLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/track/$alertId/$trackingToken': {
      id: '/track/$alertId/$trackingToken'
      path: '/track/$alertId/$trackingToken'
      fullPath: '/track/$alertId/$trackingToken'
      preLoaderRoute: typeof TrackAlertIdTrackingTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts_/edit/$contactId': {
      id: '/contacts_/edit/$contactId'
      path: '/contacts/edit/$contactId'
      fullPath: '/contacts/edit/$contactId'
      preLoaderRoute: typeof ContactsEditContactIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/liveMonitoring_/$alertId': {
      id: '/admin/liveMonitoring_/$alertId'
      path: '/liveMonitoring/$alertId'
      fullPath: '/admin/liveMonitoring/$alertId'
      preLoaderRoute: typeof AdminLiveMonitoringAlertIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emergencyLogs_/$alertId': {
      id: '/admin/emergencyLogs_/$alertId'
      path: '/emergencyLogs/$alertId'
      fullPath: '/admin/emergencyLogs/$alertId'
      preLoaderRoute: typeof AdminEmergencyLogsAlertIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/userManagement_/$userId/view': {
      id: '/admin/userManagement_/$userId/view'
      path: '/userManagement/$userId/view'
      fullPath: '/admin/userManagement/$userId/view'
      preLoaderRoute: typeof AdminUserManagementUserIdViewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/userManagement_/$userId/edit': {
      id: '/admin/userManagement_/$userId/edit'
      path: '/userManagement/$userId/edit'
      fullPath: '/admin/userManagement/$userId/edit'
      preLoaderRoute: typeof AdminUserManagementUserIdEditRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEmergencyLogsRoute: typeof AdminEmergencyLogsRoute
  AdminLiveMonitoringRoute: typeof AdminLiveMonitoringRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUserManagementRoute: typeof AdminUserManagementRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminEmergencyLogsAlertIdRoute: typeof AdminEmergencyLogsAlertIdRoute
  AdminLiveMonitoringAlertIdRoute: typeof AdminLiveMonitoringAlertIdRoute
  AdminUserManagementUserIdEditRoute: typeof AdminUserManagementUserIdEditRoute
  AdminUserManagementUserIdViewRoute: typeof AdminUserManagementUserIdViewRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEmergencyLogsRoute: AdminEmergencyLogsRoute,
  AdminLiveMonitoringRoute: AdminLiveMonitoringRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUserManagementRoute: AdminUserManagementRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminEmergencyLogsAlertIdRoute: AdminEmergencyLogsAlertIdRoute,
  AdminLiveMonitoringAlertIdRoute: AdminLiveMonitoringAlertIdRoute,
  AdminUserManagementUserIdEditRoute: AdminUserManagementUserIdEditRoute,
  AdminUserManagementUserIdViewRoute: AdminUserManagementUserIdViewRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddFirstContactRoute: AddFirstContactRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactsRoute: ContactsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  NewShortcutTokenRoute: NewShortcutTokenRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ShortcutSetupRoute: ShortcutSetupRoute,
  SignupRoute: SignupRoute,
  TestNewShortcutRoute: TestNewShortcutRoute,
  TestShortcutRoute: TestShortcutRoute,
  TriggerRoute: TriggerRoute,
  AdminLoginRoute: AdminLoginRoute,
  ContactsAddRoute: ContactsAddRoute,
  ProfileEditRoute: ProfileEditRoute,
  TestGpsAlertIdRoute: TestGpsAlertIdRoute,
  TestTrackingAlertIdRoute: TestTrackingAlertIdRoute,
  ContactsEditContactIdRoute: ContactsEditContactIdRoute,
  TrackAlertIdTrackingTokenRoute: TrackAlertIdTrackingTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
