/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TriggerRouteImport } from './routes/trigger'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShortcutSetupRouteImport } from './routes/shortcut-setup'
import { Route as SetupRouteImport } from './routes/setup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as HomeRouteImport } from './routes/home'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ContactsRouteImport } from './routes/contacts'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ProfileEditRouteImport } from './routes/profile.edit'
import { Route as ContactsAddRouteImport } from './routes/contacts_.add'
import { Route as AdminUserManagementRouteImport } from './routes/admin.userManagement'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminLiveMonitoringRouteImport } from './routes/admin.liveMonitoring'
import { Route as AdminEmergencyLogsRouteImport } from './routes/admin.emergencyLogs'

const TriggerRoute = TriggerRouteImport.update({
  id: '/trigger',
  path: '/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShortcutSetupRoute = ShortcutSetupRouteImport.update({
  id: '/shortcut-setup',
  path: '/shortcut-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRoute = SetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsRoute = ContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactsAddRoute = ContactsAddRouteImport.update({
  id: '/contacts_/add',
  path: '/contacts/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserManagementRoute = AdminUserManagementRouteImport.update({
  id: '/userManagement',
  path: '/userManagement',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveMonitoringRoute = AdminLiveMonitoringRouteImport.update({
  id: '/liveMonitoring',
  path: '/liveMonitoring',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmergencyLogsRoute = AdminEmergencyLogsRouteImport.update({
  id: '/emergencyLogs',
  path: '/emergencyLogs',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shortcut-setup': typeof ShortcutSetupRoute
  '/signup': typeof SignupRoute
  '/trigger': typeof TriggerRoute
  '/admin/emergencyLogs': typeof AdminEmergencyLogsRoute
  '/admin/liveMonitoring': typeof AdminLiveMonitoringRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/userManagement': typeof AdminUserManagementRoute
  '/contacts/add': typeof ContactsAddRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contacts': typeof ContactsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shortcut-setup': typeof ShortcutSetupRoute
  '/signup': typeof SignupRoute
  '/trigger': typeof TriggerRoute
  '/admin/emergencyLogs': typeof AdminEmergencyLogsRoute
  '/admin/liveMonitoring': typeof AdminLiveMonitoringRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/userManagement': typeof AdminUserManagementRoute
  '/contacts/add': typeof ContactsAddRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contacts': typeof ContactsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/history': typeof HistoryRoute
  '/home': typeof HomeRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/setup': typeof SetupRoute
  '/shortcut-setup': typeof ShortcutSetupRoute
  '/signup': typeof SignupRoute
  '/trigger': typeof TriggerRoute
  '/admin/emergencyLogs': typeof AdminEmergencyLogsRoute
  '/admin/liveMonitoring': typeof AdminLiveMonitoringRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/userManagement': typeof AdminUserManagementRoute
  '/contacts_/add': typeof ContactsAddRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contacts'
    | '/forgot-password'
    | '/help'
    | '/history'
    | '/home'
    | '/how-it-works'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/settings'
    | '/setup'
    | '/shortcut-setup'
    | '/signup'
    | '/trigger'
    | '/admin/emergencyLogs'
    | '/admin/liveMonitoring'
    | '/admin/settings'
    | '/admin/userManagement'
    | '/contacts/add'
    | '/profile/edit'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contacts'
    | '/forgot-password'
    | '/help'
    | '/history'
    | '/home'
    | '/how-it-works'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/settings'
    | '/setup'
    | '/shortcut-setup'
    | '/signup'
    | '/trigger'
    | '/admin/emergencyLogs'
    | '/admin/liveMonitoring'
    | '/admin/settings'
    | '/admin/userManagement'
    | '/contacts/add'
    | '/profile/edit'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contacts'
    | '/forgot-password'
    | '/help'
    | '/history'
    | '/home'
    | '/how-it-works'
    | '/login'
    | '/notifications'
    | '/privacy'
    | '/settings'
    | '/setup'
    | '/shortcut-setup'
    | '/signup'
    | '/trigger'
    | '/admin/emergencyLogs'
    | '/admin/liveMonitoring'
    | '/admin/settings'
    | '/admin/userManagement'
    | '/contacts_/add'
    | '/profile/edit'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactsRoute: typeof ContactsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  HistoryRoute: typeof HistoryRoute
  HomeRoute: typeof HomeRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SetupRoute: typeof SetupRoute
  ShortcutSetupRoute: typeof ShortcutSetupRoute
  SignupRoute: typeof SignupRoute
  TriggerRoute: typeof TriggerRoute
  ContactsAddRoute: typeof ContactsAddRoute
  ProfileEditRoute: typeof ProfileEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trigger': {
      id: '/trigger'
      path: '/trigger'
      fullPath: '/trigger'
      preLoaderRoute: typeof TriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shortcut-setup': {
      id: '/shortcut-setup'
      path: '/shortcut-setup'
      fullPath: '/shortcut-setup'
      preLoaderRoute: typeof ShortcutSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts': {
      id: '/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof ContactsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacts_/add': {
      id: '/contacts_/add'
      path: '/contacts/add'
      fullPath: '/contacts/add'
      preLoaderRoute: typeof ContactsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/userManagement': {
      id: '/admin/userManagement'
      path: '/userManagement'
      fullPath: '/admin/userManagement'
      preLoaderRoute: typeof AdminUserManagementRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/liveMonitoring': {
      id: '/admin/liveMonitoring'
      path: '/liveMonitoring'
      fullPath: '/admin/liveMonitoring'
      preLoaderRoute: typeof AdminLiveMonitoringRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emergencyLogs': {
      id: '/admin/emergencyLogs'
      path: '/emergencyLogs'
      fullPath: '/admin/emergencyLogs'
      preLoaderRoute: typeof AdminEmergencyLogsRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminEmergencyLogsRoute: typeof AdminEmergencyLogsRoute
  AdminLiveMonitoringRoute: typeof AdminLiveMonitoringRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUserManagementRoute: typeof AdminUserManagementRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminEmergencyLogsRoute: AdminEmergencyLogsRoute,
  AdminLiveMonitoringRoute: AdminLiveMonitoringRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUserManagementRoute: AdminUserManagementRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactsRoute: ContactsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  HistoryRoute: HistoryRoute,
  HomeRoute: HomeRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SetupRoute: SetupRoute,
  ShortcutSetupRoute: ShortcutSetupRoute,
  SignupRoute: SignupRoute,
  TriggerRoute: TriggerRoute,
  ContactsAddRoute: ContactsAddRoute,
  ProfileEditRoute: ProfileEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
